"""program_enrollment + background_check + role bg gate

Revision ID: 028d8b7d06f6
Revises: 92e900417990
Create Date: 2026-07-27 22:25:34.565351
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '028d8b7d06f6'
down_revision: str | None = '92e900417990'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['volunteer_profile.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_enrollment_org_id'), 'program_enrollment', ['org_id'], unique=False)
    op.create_index(op.f('ix_program_enrollment_profile_id'), 'program_enrollment', ['profile_id'], unique=False)
    op.create_index(op.f('ix_program_enrollment_program_id'), 'program_enrollment', ['program_id'], unique=False)
    # server_default backfills existing rows; then drop it — the ORM supplies the value on insert.
    op.add_column('shift_role', sa.Column('requires_background_check', sa.Boolean(),
                  nullable=False, server_default=sa.false()))
    op.alter_column('shift_role', 'requires_background_check', server_default=None)
    op.add_column('volunteer_profile', sa.Column('background_check_status', sa.String(length=20),
                  nullable=False, server_default='none'))
    op.alter_column('volunteer_profile', 'background_check_status', server_default=None)
    op.add_column('volunteer_profile', sa.Column('background_check_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer_profile', 'background_check_expires_at')
    op.drop_column('volunteer_profile', 'background_check_status')
    op.drop_column('shift_role', 'requires_background_check')
    op.drop_index(op.f('ix_program_enrollment_program_id'), table_name='program_enrollment')
    op.drop_index(op.f('ix_program_enrollment_profile_id'), table_name='program_enrollment')
    op.drop_index(op.f('ix_program_enrollment_org_id'), table_name='program_enrollment')
    op.drop_table('program_enrollment')
    # ### end Alembic commands ###
