"""form ack config

Revision ID: 03d18ac14836
Revises: eb8cf3883132
Create Date: 2026-07-28 00:35:53.677714
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '03d18ac14836'
down_revision: str | None = 'eb8cf3883132'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; then drop it — the ORM supplies "" on insert.
    op.add_column('form_definition',
                  sa.Column('ack_template_key', sa.String(length=80), nullable=False,
                            server_default=''))
    op.alter_column('form_definition', 'ack_template_key', server_default=None)
    op.add_column('form_definition',
                  sa.Column('ack_recipient_field', sa.String(length=80), nullable=False,
                            server_default=''))
    op.alter_column('form_definition', 'ack_recipient_field', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_definition', 'ack_recipient_field')
    op.drop_column('form_definition', 'ack_template_key')
    # ### end Alembic commands ###
