"""kiosk surfaces

Revision ID: 256526b8cc5e
Revises: f0e1d2c3b4a5
Create Date: 2026-07-28 05:31:48.265614
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '256526b8cc5e'
down_revision: str | None = 'f0e1d2c3b4a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiosk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('panels', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_kiosk_name')
    )
    op.create_index(op.f('ix_kiosk_org_id'), 'kiosk', ['org_id'], unique=False)
    op.create_index(op.f('ix_kiosk_token'), 'kiosk', ['token'], unique=True)
    op.create_table('kiosk_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('kiosk_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosk.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiosk_task_kiosk_id'), 'kiosk_task', ['kiosk_id'], unique=False)
    op.create_index(op.f('ix_kiosk_task_org_id'), 'kiosk_task', ['org_id'], unique=False)
    op.create_table('kiosk_task_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=False),
    sa.Column('done_note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['kiosk_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'on_date', name='uq_task_completion_day')
    )
    op.create_index(op.f('ix_kiosk_task_completion_org_id'), 'kiosk_task_completion', ['org_id'], unique=False)
    op.create_index(op.f('ix_kiosk_task_completion_task_id'), 'kiosk_task_completion', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kiosk_task_completion_task_id'), table_name='kiosk_task_completion')
    op.drop_index(op.f('ix_kiosk_task_completion_org_id'), table_name='kiosk_task_completion')
    op.drop_table('kiosk_task_completion')
    op.drop_index(op.f('ix_kiosk_task_org_id'), table_name='kiosk_task')
    op.drop_index(op.f('ix_kiosk_task_kiosk_id'), table_name='kiosk_task')
    op.drop_table('kiosk_task')
    op.drop_index(op.f('ix_kiosk_token'), table_name='kiosk')
    op.drop_index(op.f('ix_kiosk_org_id'), table_name='kiosk')
    op.drop_table('kiosk')
    # ### end Alembic commands ###
