"""social channels posts targets

Revision ID: 322f25e0bc6b
Revises: d9e046dd703f
Create Date: 2026-07-24 20:08:51.451977
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '322f25e0bc6b'
down_revision: str | None = 'd9e046dd703f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('manual', 'webhook', 'x', 'linkedin', 'mastodon', 'facebook', name='platform'), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('connection_status', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('char_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'platform', 'handle', name='uq_social_channel')
    )
    op.create_index(op.f('ix_social_channel_org_id'), 'social_channel', ['org_id'], unique=False)
    op.create_table('social_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'scheduled', 'publishing', 'published', 'partially_published', 'failed', name='poststatus'), nullable=False),
    sa.Column('source', sa.Enum('human', 'llm_assisted', name='postsource'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('agent_proposal_id', sa.Integer(), nullable=True),
    sa.Column('draft_prompt', sa.Text(), nullable=False),
    sa.Column('draft_provider', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_proposal_id'], ['agent_proposal.id'], ),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_post_org_id'), 'social_post', ['org_id'], unique=False)
    op.create_table('social_publish_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'published', 'failed', name='targetstatus'), nullable=False),
    sa.Column('external_ref', sa.String(length=300), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('outbox_event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['social_channel.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['social_post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'channel_id', name='uq_social_target')
    )
    op.create_index(op.f('ix_social_publish_target_org_id'), 'social_publish_target', ['org_id'], unique=False)
    op.create_index(op.f('ix_social_publish_target_post_id'), 'social_publish_target', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_publish_target_post_id'), table_name='social_publish_target')
    op.drop_index(op.f('ix_social_publish_target_org_id'), table_name='social_publish_target')
    op.drop_table('social_publish_target')
    op.drop_index(op.f('ix_social_post_org_id'), table_name='social_post')
    op.drop_table('social_post')
    op.drop_index(op.f('ix_social_channel_org_id'), table_name='social_channel')
    op.drop_table('social_channel')
    # ### end Alembic commands ###
