"""forms and workflows

Revision ID: 7ec3058d4c20
Revises: 322f25e0bc6b
Create Date: 2026-07-24 21:15:32.506082
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '7ec3058d4c20'
down_revision: str | None = '322f25e0bc6b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('purpose', sa.String(length=400), nullable=False),
    sa.Column('default_visibility', sa.Enum('public', 'volunteer', 'internal', name='visibility'), nullable=False),
    sa.Column('workflow_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='formdefinitionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'key', name='uq_form_definition_key')
    )
    op.create_index(op.f('ix_form_definition_org_id'), 'form_definition', ['org_id'], unique=False)
    op.create_table('workflow_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject_type', sa.String(length=60), nullable=False),
    sa.Column('initial_state', sa.String(length=60), nullable=False),
    sa.Column('states', sa.JSON(), nullable=False),
    sa.Column('transitions', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='definitionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'key', name='uq_workflow_definition_key')
    )
    op.create_index(op.f('ix_workflow_definition_org_id'), 'workflow_definition', ['org_id'], unique=False)
    op.create_table('workflow_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('workflow_definition_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=60), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='instancestatus'), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'workflow_definition_id', 'subject_type', 'subject_id', name='uq_workflow_instance_subject')
    )
    op.create_index(op.f('ix_workflow_instance_org_id'), 'workflow_instance', ['org_id'], unique=False)
    op.create_table('form_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('form_definition_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'retired', name='versionstatus'), nullable=False),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['form_definition_id'], ['form_definition.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'form_definition_id', 'version', name='uq_form_version')
    )
    op.create_index(op.f('ix_form_version_form_definition_id'), 'form_version', ['form_definition_id'], unique=False)
    op.create_index(op.f('ix_form_version_org_id'), 'form_version', ['org_id'], unique=False)
    op.create_table('workflow_approval_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('workflow_instance_id', sa.Integer(), nullable=False),
    sa.Column('transition_name', sa.String(length=80), nullable=False),
    sa.Column('required_permission', sa.String(length=80), nullable=False),
    sa.Column('required_scope', sa.String(length=20), nullable=False),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', name='approvalstatus'), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_approval_request_org_id'), 'workflow_approval_request', ['org_id'], unique=False)
    op.create_index(op.f('ix_workflow_approval_request_workflow_instance_id'), 'workflow_approval_request', ['workflow_instance_id'], unique=False)
    op.create_table('workflow_transition_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('workflow_instance_id', sa.Integer(), nullable=False),
    sa.Column('transition_name', sa.String(length=80), nullable=False),
    sa.Column('from_state', sa.String(length=60), nullable=False),
    sa.Column('to_state', sa.String(length=60), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_workflow_transition_event_org_id'), 'workflow_transition_event', ['org_id'], unique=False)
    op.create_index(op.f('ix_workflow_transition_event_workflow_instance_id'), 'workflow_transition_event', ['workflow_instance_id'], unique=False)
    op.create_table('form_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('form_definition_id', sa.Integer(), nullable=False),
    sa.Column('form_version_id', sa.Integer(), nullable=False),
    sa.Column('schema_snapshot', sa.JSON(), nullable=False),
    sa.Column('submitter_person_id', sa.Integer(), nullable=True),
    sa.Column('submitter_user_id', sa.Integer(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'under_review', 'accepted', 'rejected', 'withdrawn', name='submissionstatus'), nullable=False),
    sa.Column('workflow_instance_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['form_definition_id'], ['form_definition.id'], ),
    sa.ForeignKeyConstraint(['form_version_id'], ['form_version.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['submitter_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['submitter_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submission_form_definition_id'), 'form_submission', ['form_definition_id'], unique=False)
    op.create_index(op.f('ix_form_submission_org_id'), 'form_submission', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_submission_org_id'), table_name='form_submission')
    op.drop_index(op.f('ix_form_submission_form_definition_id'), table_name='form_submission')
    op.drop_table('form_submission')
    op.drop_index(op.f('ix_workflow_transition_event_workflow_instance_id'), table_name='workflow_transition_event')
    op.drop_index(op.f('ix_workflow_transition_event_org_id'), table_name='workflow_transition_event')
    op.drop_table('workflow_transition_event')
    op.drop_index(op.f('ix_workflow_approval_request_workflow_instance_id'), table_name='workflow_approval_request')
    op.drop_index(op.f('ix_workflow_approval_request_org_id'), table_name='workflow_approval_request')
    op.drop_table('workflow_approval_request')
    op.drop_index(op.f('ix_form_version_org_id'), table_name='form_version')
    op.drop_index(op.f('ix_form_version_form_definition_id'), table_name='form_version')
    op.drop_table('form_version')
    op.drop_index(op.f('ix_workflow_instance_org_id'), table_name='workflow_instance')
    op.drop_table('workflow_instance')
    op.drop_index(op.f('ix_workflow_definition_org_id'), table_name='workflow_definition')
    op.drop_table('workflow_definition')
    op.drop_index(op.f('ix_form_definition_org_id'), table_name='form_definition')
    op.drop_table('form_definition')
    # ### end Alembic commands ###
