"""shift reminded_at + no_show

Revision ID: 92e900417990
Revises: b073dc2285ab
Create Date: 2026-07-27 22:07:02.672919
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '92e900417990'
down_revision: str | None = 'b073dc2285ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_signup', sa.Column('reminded_at', sa.DateTime(), nullable=True))
    # server_default backfills existing rows; then drop it — the ORM supplies the value on insert.
    op.add_column('shift_signup',
                  sa.Column('no_show', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('shift_signup', 'no_show', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_signup', 'no_show')
    op.drop_column('shift_signup', 'reminded_at')
    # ### end Alembic commands ###
