"""user session_version

Revision ID: b073dc2285ab
Revises: f4c09b9d514f
Create Date: 2026-07-25 17:46:02.624055
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b073dc2285ab'
down_revision: str | None = 'f4c09b9d514f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('session_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'session_version')
    # ### end Alembic commands ###
