"""user session_version

Revision ID: b073dc2285ab
Revises: f4c09b9d514f
Create Date: 2026-07-25 17:46:02.624055
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'b073dc2285ab'
down_revision: str | None = 'f4c09b9d514f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default backfills existing rows (a bare NOT NULL add fails on a populated table);
    # then drop the default — the ORM supplies the value on insert.
    op.add_column('app_user',
                  sa.Column('session_version', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('app_user', 'session_version', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'session_version')
    # ### end Alembic commands ###
