"""content pages and revisions

Revision ID: d9e046dd703f
Revises: c1a2b3d4e5f6
Create Date: 2026-07-24 17:51:55.886931
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'd9e046dd703f'
down_revision: str | None = 'c1a2b3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='pagestatus'), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('custom_css', sa.Text(), nullable=False),
    sa.Column('custom_css_safe', sa.Text(), nullable=False),
    sa.Column('published_blocks', sa.JSON(), nullable=True),
    sa.Column('published_css', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('show_in_nav', sa.Boolean(), nullable=False),
    sa.Column('nav_order', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'slug', name='uq_content_page_slug')
    )
    op.create_index(op.f('ix_content_page_org_id'), 'content_page', ['org_id'], unique=False)
    op.create_table('content_page_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('custom_css', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['content_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_page_revision_org_id'), 'content_page_revision', ['org_id'], unique=False)
    op.create_index(op.f('ix_content_page_revision_page_id'), 'content_page_revision', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_page_revision_page_id'), table_name='content_page_revision')
    op.drop_index(op.f('ix_content_page_revision_org_id'), table_name='content_page_revision')
    op.drop_table('content_page_revision')
    op.drop_index(op.f('ix_content_page_org_id'), table_name='content_page')
    op.drop_table('content_page')
    # ### end Alembic commands ###
