"""donations module

Revision ID: eb8cf3883132
Revises: 028d8b7d06f6
Create Date: 2026-07-27 22:56:11.066357
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'eb8cf3883132'
down_revision: str | None = '028d8b7d06f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('goal_minor_units', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'closed', 'archived', name='campaignstatus'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('publish_progress', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('designations', sa.JSON(), nullable=False),
    sa.Column('suggested_amounts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'slug', name='uq_campaign_slug')
    )
    op.create_index(op.f('ix_donation_campaign_org_id'), 'donation_campaign', ['org_id'], unique=False)
    op.create_table('receipt_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('next_sequence_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'tax_year', name='uq_receipt_counter')
    )
    op.create_index(op.f('ix_receipt_counter_org_id'), 'receipt_counter', ['org_id'], unique=False)
    op.create_table('donor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('postal_address', sa.JSON(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('consent_marketing', sa.Boolean(), nullable=False),
    sa.Column('consent_source', sa.String(length=80), nullable=False),
    sa.Column('is_anonymous_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'email', name='uq_donor_email')
    )
    op.create_index(op.f('ix_donor_org_id'), 'donor', ['org_id'], unique=False)
    op.create_table('in_kind_donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('estimated_value_minor_units', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['donation_campaign.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donor.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_in_kind_donation_org_id'), 'in_kind_donation', ['org_id'], unique=False)
    op.create_table('recurring_donation_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('amount_minor_units', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('interval', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'cancelled', name='recurringstatus'), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['donation_campaign.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donor.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_donation_plan_org_id'), 'recurring_donation_plan', ['org_id'], unique=False)
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('amount_minor_units', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('kind', sa.Enum('one_time', 'recurring', name='donationkind'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'refunded', 'partially_refunded', 'failed', name='donationstatus'), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('designation_code', sa.String(length=40), nullable=False),
    sa.Column('recurring_plan_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_intent_id', sa.String(length=120), nullable=True),
    sa.Column('provider_charge_id', sa.String(length=120), nullable=True),
    sa.Column('checkout_url', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=False),
    sa.Column('refunded_minor_units', sa.Integer(), nullable=False),
    sa.Column('succeeded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['donation_campaign.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donor.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['recurring_plan_id'], ['recurring_donation_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'idempotency_key', name='uq_donation_idem')
    )
    op.create_index(op.f('ix_donation_campaign_id'), 'donation', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_donation_org_id'), 'donation', ['org_id'], unique=False)
    op.create_index(op.f('ix_donation_public_token'), 'donation', ['public_token'], unique=False)
    op.create_table('donation_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=True),
    sa.Column('in_kind_donation_id', sa.Integer(), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=40), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donation.id'], ),
    sa.ForeignKeyConstraint(['in_kind_donation_id'], ['in_kind_donation.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('donation_id', name='uq_receipt_donation'),
    sa.UniqueConstraint('org_id', 'tax_year', 'sequence_no', name='uq_receipt_sequence')
    )
    op.create_index(op.f('ix_donation_receipt_org_id'), 'donation_receipt', ['org_id'], unique=False)
    op.create_table('payment_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_event_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload_digest', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donation.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'provider', 'provider_event_id', name='uq_payment_event')
    )
    op.create_index(op.f('ix_payment_event_org_id'), 'payment_event', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_event_org_id'), table_name='payment_event')
    op.drop_table('payment_event')
    op.drop_index(op.f('ix_donation_receipt_org_id'), table_name='donation_receipt')
    op.drop_table('donation_receipt')
    op.drop_index(op.f('ix_donation_public_token'), table_name='donation')
    op.drop_index(op.f('ix_donation_org_id'), table_name='donation')
    op.drop_index(op.f('ix_donation_campaign_id'), table_name='donation')
    op.drop_table('donation')
    op.drop_index(op.f('ix_recurring_donation_plan_org_id'), table_name='recurring_donation_plan')
    op.drop_table('recurring_donation_plan')
    op.drop_index(op.f('ix_in_kind_donation_org_id'), table_name='in_kind_donation')
    op.drop_table('in_kind_donation')
    op.drop_index(op.f('ix_donor_org_id'), table_name='donor')
    op.drop_table('donor')
    op.drop_index(op.f('ix_receipt_counter_org_id'), table_name='receipt_counter')
    op.drop_table('receipt_counter')
    op.drop_index(op.f('ix_donation_campaign_org_id'), table_name='donation_campaign')
    op.drop_table('donation_campaign')
    # ### end Alembic commands ###
