"""approval consumed_at

Revision ID: f4c09b9d514f
Revises: 7ec3058d4c20
Create Date: 2026-07-24 21:24:58.841367
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f4c09b9d514f'
down_revision: str | None = '7ec3058d4c20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_approval_request', sa.Column('consumed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_approval_request', 'consumed_at')
    # ### end Alembic commands ###
